### ISSUE TITLE
Eigene Bilder von Startseite

### ISSUE THREAD

**Issue by fraeggle** [ei23com/diy-smart-home#2]
Hi Felix.

Beim Update solltest du eventuell erwähnen seine eigenen erstellten Bilder für die Startseite zu kopieren und nach dem Upgrade ins web/static/img wieder einzufügen. Sonst sind die wech... (bzw liegen in im web/static/img/img)
War zumindest bei mir so

Gruß Peter

**Comment by ei23fxg** [comment]
Dann hab ich mich hier wohl vertippt:
https://github.com/ei23com/diy-smart-home/blob/main/ei23.sh#L175

Korrigiere ich gleich.
Danke Peter!

**Comment by fraeggle** [comment]
gern  und danke  super Job.....
