### ISSUE TITLE
Minor:     diy-smart-home/DOCS/DE/docs/software  Links to FAQ page not working

### ISSUE THREAD

**Issue by Roehrenzauber** [ei23com/diy-smart-home#3]
Inside the individual mark down software derscription, the link to the FAQ page does not work.
#Noch im Aufbau

Ich verweise zunächst auf die [Häufigen Fragen - FAQ](https://github.com/ei23com/diy-smart-home/blob/main/start/faq)

**Comment by ei23fxg** [comment]
If you are using the DOCS on GitHub; It's not intended to use on Github.
Use the compiled pages, links are working there.
[diy-smart-home.ei23.de](https://diy-smart-home.ei23.de/)
[diy-smart-home.ei23.com](https://diy-smart-home.ei23.com/)
